services:
  homeassistant:
    container_name: gitops-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - /data/hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports: 
      - 8123:8123
    environment:
      TZ: Europe/Zurich
  
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: gitops-matter-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - /data/hass/matter-data:/data/
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
      #- /dev/hci0
  
  traefik:
    image: "traefik"
    restart: always
    container_name: gitops-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: gitops-n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.routers.n8n.priority=10
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
  
  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    container_name: gitops-ts-nginx
    privileged: true
    environment:
      - TZ=Europe/Berlin
      - TS_AUTHKEY=${TS_AUTHKEY}
      #- TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=0
      - TS_ROUTES=192.168.1.0/24
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    container_name: gitops-ts-nginx-support
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
    restart: unless-stopped
  
  watchtower:
    container_name: gitops-watchtower
    image: containrrr/watchtower:latest
    mem_limit: 256m
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=false
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - TZ=Europe/Zurich
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  hvss:
    container_name: gitops-hvss
    image: ewproductsecurity/hvss-calculator-service:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.hvss.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`) && (PathPrefix(`/hvss`) || PathPrefix(`/hvss/`))
      - traefik.http.routers.hvss.tls=true
      - traefik.http.routers.hvss.entrypoints=web,websecure
      - traefik.http.routers.hvss.tls.certresolver=mytlschallenge
      - traefik.http.routers.hvsss.priority=100
      - traefik.http.middlewares.hvss.headers.SSLRedirect=true
      - traefik.http.middlewares.hvss.headers.STSSeconds=315360000
      - traefik.http.middlewares.hvss.headers.browserXSSFilter=true
      - traefik.http.middlewares.hvss.headers.contentTypeNosniff=true
      - traefik.http.middlewares.hvss.headers.forceSTSHeader=true
      - traefik.http.middlewares.hvss.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.hvss.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.hvss.headers.STSPreload=true
      - traefik.http.routers.hvss.middlewares=hvss@docker
    mem_limit: 64m
    ports:
      - "127.0.0.1:8088:8088"
    restart: always
  
  signal-cli-rest-api:
    container_name: gitops-signal-cli
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8087:8080" #map docker port 8080 to host port 8080.
    volumes:
      #- "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
      - signal_data:/home/.local/share/signal-cli
  #knxd:
  #  image: ghcr.io/cyberatz/knxd:amd64
  #  container_name: knxd
  #  privileged: true
  #  environment:
  #    - TZ=Europe/Zurich
  #  #ports:
  #  #  - "3672:3672/udp"
  #  #  - "6720:6720/tcp"
  #  #network_mode: "host"
  #  #networks:
  #  #    #default:
  #  #    lan:
  #  #      ipv4_address: 10.0.0.33
  #  #      ipv6_address: '2001:1a88:195:7900::33'
  #  network_mode: "service:homeassistant"
  #  #entrypoint: ["tail", "-f", "/dev/null"]
  #  restart: unless-stopped
  #  volumes:
  #    - /data/ha/knxd:/etc/knxd
  #  healthcheck:
  #    test: "/home/docker-healthcheck"
  #    interval: 60s
  #    retries: 200

  #postgres:
  #  container_name: postgres 
  #  image: postgres:13
  #  restart: always
  #  mem_limit: 256m
  #  environment:
  #    - TZ=Europe/Zurich
  #    - POSTGRES_PASSWORD=p@ssw0rd1234567890
  #    - PGDATA=/var/lib/postgresql/data/pgdata
  #  volumes:
  #    - /data/ha/postgres/postgres.conf:/etc/postgresql/postgresql.conf
  #    - /data/ha/postgres/data:/var/lib/postgresql/data
  #  #network_mode: "service:homeassistant"
  #  #ports:
  #  #  - 5432:5432

  #pg-adminer:
  #  container_name: adminer
  #  image: adminer:latest
  #  restart: always
  #  #mem_limit: 256m
  #  #network_mode: "service:homeassistant"
  #  ports:
  #    - 8090:8080
    
  #mqtt:
  #   image: eclipse-mosquitto:latest
  #   container_name: mqtt
  #   mem_limit: 64m
  #   #network_mode: "service:homeassistant"
  #   ports:
  #     - "1883:1883/tcp"
  #     - "9001:9001/tcp"
  #   restart: always
  #   volumes:
  #     - /data/ha/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf 
  #     - /data/ha/mosquitto/data:/mosquitto/data 
  #     - /data/ha/mosquitto/log:/mosquitto/log 

  #knxweather:
  #  container_name: knxweather
  #  image: andrevs/online_knx_weatherstation:latest
  #  restart: always
  #  mem_limit: 64m
  #  environment:
  #    TZ: Europe/Zurich

  #homeassistant:
  #  container_name: home-assistant
  #  image: homeassistant/home-assistant:stable
  #  #mem_limit: 1024m
  #  volumes:
  #    - /data/ha/homeassistant:/config
  #  environment:
  #    - TZ=Europe/Zurich
  #  restart: always
  #  extra_hosts:
  #  #  - "postgres:127.0.0.1"
  #  #  - "mqtt:127.0.0.1"
  #    - "knxd:127.0.0.1"
      
  #  #network_mode: host
  #  networks:
  #      lan:
  #          ipv4_address: 10.0.0.32
  #          ipv6_address: '2a05:41c0:100:2800::32'
  #      default:

  hass-configurator:
    container_name: hass-configurator
    image: "causticlab/hass-configurator-docker:x86_64"
    environment:
      - TZ=Europe/Zurich
    restart: always
    #network_mode: "service:homeassistant"
    ports:
      - "3218:3218/tcp"
    mem_limit: 64m
    volumes:
      - /data/hass/homeassistant-configurator:/config
      - /data/hass:/hass-config



volumes:
  n8n_data:
  traefik_data:
  signal_data:


#networks:
#  lan:
#    external:
#      name: lan
#  default:
#    driver: bridge
